version: 2

project_name: portik

before:
  hooks:
    - go mod download
    - sh -c 'export GORELEASER_CURRENT_TAG=$(cat VERSION) || echo "v0.0.0"'

builds:
  - id: portik
    main: .
    binary: portik
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/pratik-anurag/portik/internal/cli.version={{.Tag}} -X github.com/pratik-anurag/portik/internal/cli.commit={{ .ShortCommit }}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

snapshot:
  name_template: "{{ .Version }}-next"

changelog:
  use: github
